<template>
  <div class="container align-center">
    <h3 class="titles">Skills <img class="gear rotate-gear" src="../../assets/gear.png"></h3>

    <div v-for="skill in skills" :key="skill.id" class="icons-meters">
      <label class="labels" :for="skill.id"><img class="icons" :src="skill.icon">
        {{ skill.name }}
      </label>
      <meter :id="skill.id" :value="skill.value" min="0" max="10" low="1" high="1"></meter>
    </div>
  </div>
</template>

<script>
let skills = require('../../assets/skills.json')

export default {
  data() { return { skills } }
}
</script>

<style>
.gear {
  width: 30px;
  opacity: 70%;
  margin: 0 10px;
}

.rotate-gear {
  -webkit-animation: rotate-center 4s linear infinite both;
  animation: rotate-center 4s linear infinite both;
}

.icons-meters {
  margin: 5px 0;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.icons {
  width: 20px;
  margin: 5px 10px;
}

.meters {
  margin-bottom: 40px;
}

.labels {
  display: flex;
  align-items: center;
  color: whitesmoke;
  font-size: 1.1em;
}

meter {
  display: flex;
  margin: 0 15px;
  width: 70%;
  align-items: flex-end;
  height: 15px;
}

@media (max-width: 750px) {
  meter {
    width: 60%;
  }
}

@media (max-width: 600px) {
  meter {
    width: 50%;
  }
}

@media (max-width: 450px) {
  meter {
    width: 36%;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-11-25 14:30:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }

  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }

  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
</style>