<template>
  <div class="my-name name-about">
    <h1 class="name animation-typing">Citadin</h1>
    <h2 class="subtitle">Fullstack Developer</h2>
  </div>


  <div class="resume container align-center">
    <h3 class="titles">Resume</h3>

    <p class="resume-text">I'm a technology autodidact. I've been studying fullstack development for 1 year. I always
      seek to bring quality
      to
      my applications, with the best methodologies, technologies and metrics, bringing a final product of value and
      maintainability.
    </p>
    <p class="resume-text">
      I'm a functional languages enthusiast. My favorite technologies are Elixir and Rust, but I also have skills in
      Javascript, Typescript, NodeJS, ExpressJS, VueJS, NuxtJS. In databases, I have knowledge in PostgreSQL and
      MongoDB.
    </p>
    <p class="resume-text">
      I'm looking for my first job opportunity. I'm sure I'm prepared for whatever it takes, and if I don't know some
      necessary technology, I can learn easily and quickly.
    </p>
  </div>

  <div class="skills container align-center">
    <h3 class="titles">Skills <img class="gear rotate-gear" src="../assets/gear.png"></h3>

    <div class="meters align-center">
      <div class="icons-meters">
        <label class="labels" for="js"><img src="../assets/icons/javascript-original.svg"
            class="icons" />Javascript</label>
        <meter id="js" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="ts"><img src="../assets/icons/typescript-original.svg"
            class="icons" />Typescript</label>
        <meter id="ts" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="vue"><img src="../assets/icons/vuejs-original.svg" class="icons" />VueJS</label>
        <meter id="vue" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="nuxt"><img src="../assets/icons/nuxtjs-original.svg" class="icons" />NuxtJS</label>
        <meter id="nuxt" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="node"><img src="../assets/icons/nodejs-original.svg" class="icons" />NodeJS</label>
        <meter id="node" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="express"><img src="../assets/icons/express-original.svg"
            class="icons" />ExpressJS</label>
        <meter id="express" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="rust"><img src="../assets/icons/rust-plain.svg" class="icons" />Rust</label>
        <meter id="rust" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="elixir"><img src="../assets/icons/elixir-original.svg" class="icons" />Elixir</label>
        <meter id="elixir" value="8" min="0" max="10"></meter>
      </div>

      <div class="icons-meters">
        <label class="labels" for="psql"><img src="../assets/icons/postgresql-original.svg"
            class="icons" />PostgreSQL</label>
        <meter id="psql" value="8" min="0" max="10"></meter>
      </div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>
.name-about {
  margin: 80px auto 20px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.subtitle {
  margin: 10px 0 60px;
}

.titles {
  color: #b6b6b6;
  font-size: 1.4em;
  display: flex;
  margin-bottom: 30px;
}

.gear {
  width: 30px;
  opacity: 70%;
  margin: 0 10px;
}

.container {
  width: 80%;
  max-width: 800px;
  margin: 20px auto;
}

.resume {
  margin: 0 auto 40px;
}

.resume-text {
  font-size: 1.2em;
  margin-bottom: 40px;
  text-align: justify;
  color: #f5f5f5;
}

.icons-meters {
  margin: 5px 0;
  display: flex;
  justify-content: space-between;
}

.meters {
  margin-bottom: 40px;
}

.labels {
  display: flex;
  align-items: center;
  color: whitesmoke;
  font-size: 1.1em;
}

meter {
  display: flex;
  margin: 0 15px;
  width: 70%;
  align-items: flex-end;
}

.icons {
  width: 20px;
  margin: 5px 10px;
}

.rotate-gear {
  -webkit-animation: rotate-center 4s linear infinite both;
  animation: rotate-center 4s linear infinite both;
}

@media (max-width: 750px) {
  meter {
    width: 60%;
  }
}

@media (max-width: 600px) {
  meter {
    width: 50%;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-11-25 14:30:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }

  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }

  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
</style>